const cookieParser = require('cookie-parser');
const express=require('express');
const app=express();
app.use(express.json());
app.use(cookieParser());
const Router=require('./Routes/userAuth');
const ProblemRouter=require('./Routes/ProblemRoutes');
app.use('/user',Router);
app.use('/admin',ProblemRouter);
module.exports=app;